import Head from "next/head";
import React from "react";
import { signIn, useSession } from "next-auth/react";
import { Footer } from "@/components/layouts/Footer";
import { Navbar } from "@/components/layouts/Navbar";

type Props = {
  children: React.ReactNode;
};

export const Layout = ({ children }: Props) => {
  const { data, status } = useSession();

  console.log(data, status);
  if (!data && status === "loading") {
    return <>Loading...</>;
  }

  // if (!data && status === "unauthenticated") {
  //   return (
  //     <>
  //       <div>ログインしてください</div>
  //       <div>
  //         <button className="btn btn-outline" onClick={() => signIn("google")}>
  //           Googleでログイン
  //         </button>
  //       </div>
  //       <div>
  //         <button className="btn btn-outline">Twitterでログイン</button>
  //       </div>
  //     </>
  //   );
  // }
  return (
    <>
      <Head>
        <title>Ticket Tool</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className="w-full max-w-lg flex justify-center m-auto pr-8 pl-8">
          {children}
        </div>
      </main>
      <Footer />
    </>
  );
};
